apiVersion: apps/v1
kind: StatefulSet
metadata:
  labels:
    app: nginx
    biglabel: "123456789012345678901234567890123456789012345678901234567890123456789012345678901234567890"
  name: nginx
spec:
  serviceName: nginx
  replicas: 1
  selector:
    matchLabels:
      app: nginx
  template:
    metadata:
      labels:
        app: nginx
    spec:
      containers:
      - image: nginx
        name: nginx
        ports:
        - containerPort: 80
          name: name5678901234567890
